remote_theme: b2a3e8/jekyll-theme-console
plugins:
- jekyll-remote-theme
- jekyll-seo-tag
title: TheTuxis - Desarrollador Full Stack
description: Portfolio y proyectos de un desarrollador apasionado por Python, Django, DevOps, ML y más. Explora más de 50 repositorios de código abierto.
author: TheTuxis
show_downloads: false
google_analytics: 
github:
  owner_name: TheTuxis
  owner_url: https://github.com/TheTuxis

header_pages:
  - index.md
  - peter.md
  - about.md
  - contact.md

style: dark

footer: ''

# Build settings
markdown: kramdown
